### ISSUE TITLE
Error while trying to compile

### ISSUE THREAD

**Issue by adrianogil** [alexanderthclark/LaTeX-Book-Template#1]
Hi, I got an error while trying to compile the current main version (5838bb4):

```
 LaTeX Error: File `kdp.cls' not found.
 ```
 
 It seems this 'kdp.cls' is missing.

**Comment by alexanderthclark** [comment]
Hi @adrianogil you can find that file at [github.com/JenniferMack/latex-kdp](https://github.com/JenniferMack/latex-kdp).

**Comment by alexanderthclark** [comment]
Thanks for highlighting. Alternatively, you can use the book class instead with `\documentclass{book}`. I'll add a comment in the main.tex file.
